project:
  type: website
  output-dir: docs

website:
  title: Muireann Ryle
  favicon: favicon.png
  navbar:
    title: false
    logo: Logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects/index.qmd
        text: Projects
    right:
      - href: cv.pdf
        text: CV
        target: _blank
  page-footer:
   left: "Copyright © 2026 Muireann Ryle"
   right:
    - icon: github
      href: https://github.com/muireann-ryle
    - icon: linkedin
      href: https://www.linkedin.com/in/muireann-ryle-2797242a0/
    - icon: envelope
      href: mailto:muireann.ryle2@mail.dcu.ie

format:
  html:
    theme: 
      - Lux 
      - styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full





  

