project:
  type: website
  output-dir: docs

website:
  title: Muireann Ryle
  favicon: favicon.png
  navbar:
    title: false
    logo: Logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects/index.qmd
        text: Projects

format:
  html:
    theme: 
      - Lux 
      - styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full


footer: |
  © 2025 Muireann Ryle · MSc Business Analytics, DCU  
  [LinkedIn](https://www.linkedin.com) · [GitHub](https://github.com) · [Email](mailto:your@email.com)
