project:
  type: website
  output-dir: docs

website:
  title: Muireann Ryle
  favicon: favicon.png
  navbar:
    title: false
    logo: Logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects/index.qmd

format:
  html:
    theme: 
      - Lux 
      - styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full



