---
title: ""
format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
page-layout: full
---
<h1 class="name-title">Muireann Ryle</h1>
<h2 class="masters-subtitle">MSc in Business Analytics</h2>

<div class="welcome-section">
<h2>Welcome to my E‑Portfolio</h2>
<div class="welcome-accent"></div>

<p>This site showcases my academic journey, technical projects, and reflections throughout the MSc in
Business Analytics. </p>
</div>
---
<div class="home-grid">

<div class="home-card">
<h2 class = "light-pink-text"> About Me </h2>
<p>You can learn more [about me](about.qmd) and my academic background, skills, and interests.</p>

</div>

<div class="home-card">
<h2 class = "light-pink-text"> My Projects </h2>
<p>A collection of [my projects](Projects/) including coursework and challenge based learning analytics projects are available to explore.</p>

</div>

</div>

<div class="home-grid">

<div class="home-card">
<h2 class = "light-pink-text"> My Reflection </h2>
<p>You can read [my reflections](reflection.qmd) about the journey of creating an E-Portfolio. This includes my thoughts of the project, skills acquired, and future steps I may take.</p>

</div>

<div class="home-card">
<h2 class = "light-pink-text"> Contact Me! </h2>
<p>You can find the best ways to [contact me](contact.qmd) to chat more about my academic journey, interests, career development, or more.</p>

</div>

</div>
