---
title: "Reflecting on Building my E‑Portfolio"
---
Creating this E-Portfolio allowed me to explore and strengthen my **technical**, **analytical**, and 
**communication** skills. It was an extremely useful introduction to **Quarto**, **GitHub**, and **SCSS**. The practical element
of building the E-Portfolio while initially learning the skills allowed me to gain a better understanding
of these tools.

## My learning experience
### The Starting Point
Prior to this project I had not worked with Quarto, VScode, GitHub, or SCSS. I found it overwhelming at first
to be introduced to multiple different methods of building the site. During each lecture we were taught
new terminology and methods which was difficult at first. However, we performed pratcical exercises
during the classes which was a big help in developing the skills and gaining a better understanding of the
concepts. 

### Key Skills Developed:
* Building a multi-page Quarto website
* Managing the site using Git and publishing pages using GitHub
* Embedding active Python code in Quarto
* Using SCSS to customise the website style
* Structuring the website to be professional and usable

### Key Resources used
The main resource which helped me throughout the building process were the lecture slides provided
by our lecturer, Damien Dupré. These helpful resources can be found on Damien's own website [here](https://damien-dupre.github.io/courses/BAA1104.html).


<div class="diagram-wrapper">
<h2 class = "light-pink-text"> The Development Process! </h2>

```{mermaid}
flowchart TD
    classDef pink fill:#f9e4ec,stroke:#d4789f,color:#1b2a4a
    classDef navy fill:#1b2a4a,stroke:#1b2a4a,color:#ffffff
    classDef endNode fill:#d4789f,stroke:#d4789f,color:#ffffff

    A[Set up GitHub repo and rendered Quarto site] --> B[Designed site structure using template]
    B --> C[Created About page with images & icons]
    C --> D[Added logo and favicon]
    D --> E[Customised design using styles.scss]
    E --> F[Added Projects section with grid & Python code]
    F --> G[Added Reflections & Contact pages with icons & diagram]
    G --> H[Ensured navbar & footer with CV, LinkedIn & GitHub links]
    H --> I{E-Portfolio available online!}

    class A,B,C,D,E,F,G,H pink
    class I endNode
```

</div>